### ISSUE TITLE
Update to new bokeh version

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwave-examples/factoring-notebook#9]
Currently we pin to bokeh===0.12.15, it would be nice to update to the latest, 2.2.2. 
However, 2.2.2 does not support Python 3.5. The previous version, which does support 3.5, is 1.4.0. Unfortunately, between 1.4.0 and 2.2.2 there is a deprecation that affects this JN: "Importing from_networkx from bokeh.models.graphs is deprecated. Import from bokeh.plotting instead."
So better to wait till after 3.5 is no longer supported.

See https://github.com/dwavesystems/dwave-ocean-sdk/issues/91  

I have the code change here for when we do: https://github.com/JoelPasvolsky/factoring-notebook/tree/bokeh

**Comment by randomir** [comment]
I don't see why would this would be a blocker.

Just unpin `bokeh` in your requirements, so that the latest version available for the current python is installed.

And then do a conditional import by replacing [line 27 on your branch](https://github.com/JoelPasvolsky/factoring-notebook/blob/4bcef4ef80281cc5b9be89439e3d5b42fb5d7205/helpers/draw.py#L27) with:
```
try:
    from bokeh.plotting import from_networkx
except ImportError:
    # handle bokeh<=1.4.0 (py35 and before)
    from bokeh.models.graphs import from_networkx
```
